/**
 * Code generated by protoc-gen-tsjson. DO NOT EDIT.
 * versions:
 * 	protoc-gen-tsjson v0.5.2
 * 	protoc            v3.10.1
 * source: flags.proto
 */


/** An enum */
export enum FlagType {
	/** An enum value */
	CKF_UNDEFINED_UNKNOWN = 0,
	/** An enum value */
	CKF_TOKEN_PRESENT = 1,
	/** An enum value */
	CKF_REMOVABLE_DEVICE = 2,
	/** An enum value */
	CKF_HW_SLOT = 3,
	/** An enum value */
	CKF_RNG = 4,
	/** An enum value */
	CKF_WRITE_PROTECTED = 5,
	/** An enum value */
	CKF_LOGIN_REQUIRED = 6,
	/** An enum value */
	CKF_USER_PIN_INITIALIZED = 7,
	/** An enum value */
	CKF_RESTORE_KEY_NOT_NEEDED = 8,
	/** An enum value */
	CKF_CLOCK_ON_TOKEN = 9,
	/** An enum value */
	CKF_PROTECTED_AUTHENTICATION_PATH = 10,
	/** An enum value */
	CKF_DUAL_CRYPTO_OPERATIONS = 11,
	/** An enum value */
	CKF_TOKEN_INITIALIZED = 12,
	/** An enum value */
	CKF_SECONDARY_AUTHENTICATION = 13,
	/** An enum value */
	CKF_USER_PIN_COUNT_LOW = 14,
	/** An enum value */
	CKF_USER_PIN_FINAL_TRY = 15,
	/** An enum value */
	CKF_USER_PIN_LOCKED = 16,
	/** An enum value */
	CKF_USER_PIN_TO_BE_CHANGED = 17,
	/** An enum value */
	CKF_SO_PIN_COUNT_LOW = 18,
	/** An enum value */
	CKF_SO_PIN_FINAL_TRY = 19,
	/** An enum value */
	CKF_SO_PIN_LOCKED = 20,
	/** An enum value */
	CKF_SO_PIN_TO_BE_CHANGED = 21,
	/** An enum value */
	CKF_ERROR_STATE = 22,
	/** An enum value */
	CKF_RW_SESSION = 23,
	/** An enum value */
	CKF_SERIAL_SESSION = 24,
	/** An enum value */
	CKF_ARRAY_ATTRIBUTE = 25,
	/** An enum value */
	CKF_HW = 26,
	/** An enum value */
	CKF_ENCRYPT = 27,
	/** An enum value */
	CKF_DECRYPT = 28,
	/** An enum value */
	CKF_DIGEST = 29,
	/** An enum value */
	CKF_SIGN = 30,
	/** An enum value */
	CKF_SIGN_RECOVER = 31,
	/** An enum value */
	CKF_VERIFY = 32,
	/** An enum value */
	CKF_VERIFY_RECOVER = 33,
	/** An enum value */
	CKF_GENERATE = 34,
	/** An enum value */
	CKF_GENERATE_KEY_PAIR = 35,
	/** An enum value */
	CKF_WRAP = 36,
	/** An enum value */
	CKF_UNWRAP = 37,
	/** An enum value */
	CKF_DERIVE = 38,
	/** An enum value */
	CKF_EC_F_P = 39,
	/** An enum value */
	CKF_EC_F_2M = 40,
	/** An enum value */
	CKF_EC_ECPARAMETERS = 41,
	/** An enum value */
	CKF_EC_NAMEDCURVE = 42,
	/** An enum value */
	CKF_EC_UNCOMPRESS = 43,
	/** An enum value */
	CKF_EC_COMPRESS = 44,
	/** An enum value */
	CKF_EXTENSION = 45,
	/** An enum value */
	CKF_LIBRARY_CANT_CREATE_OS_THREADS = 46,
	/** An enum value */
	CKF_OS_LOCKING_OK = 47,
	/** An enum value */
	CKF_DONT_BLOCK = 48,
	/** An enum value */
	CKF_NEXT_OTP = 49,
	/** An enum value */
	CKF_EXCLUDE_TIME = 50,
	/** An enum value */
	CKF_EXCLUDE_COUNTER = 51,
	/** An enum value */
	CKF_EXCLUDE_CHALLENGE = 52,
	/** An enum value */
	CKF_EXCLUDE_PIN = 53,
	/** An enum value */
	CKF_USER_FRIENDLY_OTP = 54,
}

