/**
 * Code generated by protoc-gen-tsjson. DO NOT EDIT.
 * versions:
 * 	protoc-gen-tsjson v0.5.3
 * 	protoc            v3.10.1
 * source: hashalg.proto
 */


/** An enum */
export enum HashingAlgorithm {
	/** An enum value */
	CKG_MGF1_UNDEFINED_UNKNOWN = 0,
	/** An enum value */
	CKG_MGF1_SHA1 = 1,
	/** An enum value */
	CKG_MGF1_SHA224 = 5,
	/** An enum value */
	CKG_MGF1_SHA256 = 2,
	/** An enum value */
	CKG_MGF1_SHA384 = 3,
	/** An enum value */
	CKG_MGF1_SHA512 = 4,
	/** An enum value */
	CKG_MGF1_SHA3_224 = 6,
	/** An enum value */
	CKG_MGF1_SHA3_256 = 7,
	/** An enum value */
	CKG_MGF1_SHA3_384 = 8,
	/** An enum value */
	CKG_MGF1_SHA3_512 = 9,
}

