/**
 * Code generated by protoc-gen-tsjson. DO NOT EDIT.
 * versions:
 * 	protoc-gen-tsjson v0.5.3
 * 	protoc            v3.10.1
 * source: keytypes.proto
 */


/** An enum */
export enum KeyType {
	/** An enum value */
	CKK_UNDEFINED_UNKNOWN = 0,
	/** An enum value */
	CKK_RSA = 1,
	/** An enum value */
	CKK_DSA = 2,
	/** An enum value */
	CKK_DH = 3,
	/** An enum value */
	CKK_ECDSA = 4,
	/** An enum value */
	CKK_EC = 5,
	/** An enum value */
	CKK_X9_42_DH = 6,
	/** An enum value */
	CKK_KEA = 7,
	/** An enum value */
	CKK_GENERIC_SECRET = 8,
	/** An enum value */
	CKK_RC2 = 9,
	/** An enum value */
	CKK_RC4 = 10,
	/** An enum value */
	CKK_DES = 11,
	/** An enum value */
	CKK_DES2 = 12,
	/** An enum value */
	CKK_DES3 = 13,
	/** An enum value */
	CKK_CAST = 14,
	/** An enum value */
	CKK_CAST3 = 15,
	/** An enum value */
	CKK_CAST5 = 16,
	/** An enum value */
	CKK_CAST128 = 17,
	/** An enum value */
	CKK_RC5 = 18,
	/** An enum value */
	CKK_IDEA = 19,
	/** An enum value */
	CKK_SKIPJACK = 20,
	/** An enum value */
	CKK_BATON = 21,
	/** An enum value */
	CKK_JUNIPER = 22,
	/** An enum value */
	CKK_CDMF = 23,
	/** An enum value */
	CKK_AES = 24,
	/** An enum value */
	CKK_BLOWFISH = 25,
	/** An enum value */
	CKK_TWOFISH = 26,
	/** An enum value */
	CKK_SECURID = 27,
	/** An enum value */
	CKK_HOTP = 28,
	/** An enum value */
	CKK_ACTI = 29,
	/** An enum value */
	CKK_CAMELLIA = 30,
	/** An enum value */
	CKK_ARIA = 31,
	/** An enum value */
	CKK_SHA512_224_HMAC = 32,
	/** An enum value */
	CKK_SHA512_256_HMAC = 33,
	/** An enum value */
	CKK_SHA512_T_HMAC = 34,
	/** An enum value */
	CKK_SHA_1_HMAC = 35,
	/** An enum value */
	CKK_SHA224_HMAC = 36,
	/** An enum value */
	CKK_SHA256_HMAC = 37,
	/** An enum value */
	CKK_SHA384_HMAC = 38,
	/** An enum value */
	CKK_SHA512_HMAC = 39,
	/** An enum value */
	CKK_SEED = 40,
	/** An enum value */
	CKK_GOSTR3410 = 41,
	/** An enum value */
	CKK_GOSTR3411 = 42,
	/** An enum value */
	CKK_GOST28147 = 43,
	/** An enum value */
	CKK_SHA3_224_HMAC = 44,
	/** An enum value */
	CKK_SHA3_256_HMAC = 45,
	/** An enum value */
	CKK_SHA3_384_HMAC = 46,
	/** An enum value */
	CKK_SHA3_512_HMAC = 47,
	/** An enum value */
	CKK_VENDOR_DEFINED = 48,
}

