/**
 * Code generated by protoc-gen-tsjson. DO NOT EDIT.
 * versions:
 * 	protoc-gen-tsjson v0.5.2
 * 	protoc            v3.10.1
 * source: mechanisms.proto
 */


/** An enum */
export enum MechanismType {
	/** An enum value */
	CKM_UNDEFINED_UNKNOWN = 0,
	/** An enum value */
	CKM_RSA_PKCS_KEY_PAIR_GEN = 1,
	/** An enum value */
	CKM_RSA_PKCS = 2,
	/** An enum value */
	CKM_RSA_9796 = 3,
	/** An enum value */
	CKM_RSA_X_509 = 4,
	/** An enum value */
	CKM_MD2_RSA_PKCS = 5,
	/** An enum value */
	CKM_MD5_RSA_PKCS = 6,
	/** An enum value */
	CKM_SHA1_RSA_PKCS = 7,
	/** An enum value */
	CKM_RIPEMD128_RSA_PKCS = 8,
	/** An enum value */
	CKM_RIPEMD160_RSA_PKCS = 9,
	/** An enum value */
	CKM_RSA_PKCS_OAEP = 10,
	/** An enum value */
	CKM_RSA_X9_31_KEY_PAIR_GEN = 11,
	/** An enum value */
	CKM_RSA_X9_31 = 12,
	/** An enum value */
	CKM_SHA1_RSA_X9_31 = 13,
	/** An enum value */
	CKM_RSA_PKCS_PSS = 14,
	/** An enum value */
	CKM_SHA1_RSA_PKCS_PSS = 15,
	/** An enum value */
	CKM_DSA_KEY_PAIR_GEN = 16,
	/** An enum value */
	CKM_DSA = 17,
	/** An enum value */
	CKM_DSA_SHA1 = 18,
	/** An enum value */
	CKM_DSA_FIPS_G_GEN = 19,
	/** An enum value */
	CKM_DSA_SHA224 = 20,
	/** An enum value */
	CKM_DSA_SHA256 = 21,
	/** An enum value */
	CKM_DSA_SHA384 = 22,
	/** An enum value */
	CKM_DSA_SHA512 = 23,
	/** An enum value */
	CKM_DSA_SHA3_224 = 24,
	/** An enum value */
	CKM_DSA_SHA3_256 = 25,
	/** An enum value */
	CKM_DSA_SHA3_384 = 26,
	/** An enum value */
	CKM_DSA_SHA3_512 = 27,
	/** An enum value */
	CKM_DH_PKCS_KEY_PAIR_GEN = 28,
	/** An enum value */
	CKM_DH_PKCS_DERIVE = 29,
	/** An enum value */
	CKM_X9_42_DH_KEY_PAIR_GEN = 30,
	/** An enum value */
	CKM_X9_42_DH_DERIVE = 31,
	/** An enum value */
	CKM_X9_42_DH_HYBRID_DERIVE = 32,
	/** An enum value */
	CKM_X9_42_MQV_DERIVE = 33,
	/** An enum value */
	CKM_SHA256_RSA_PKCS = 34,
	/** An enum value */
	CKM_SHA384_RSA_PKCS = 35,
	/** An enum value */
	CKM_SHA512_RSA_PKCS = 36,
	/** An enum value */
	CKM_SHA256_RSA_PKCS_PSS = 37,
	/** An enum value */
	CKM_SHA384_RSA_PKCS_PSS = 38,
	/** An enum value */
	CKM_SHA512_RSA_PKCS_PSS = 39,
	/** An enum value */
	CKM_SHA224_RSA_PKCS = 40,
	/** An enum value */
	CKM_SHA224_RSA_PKCS_PSS = 41,
	/** An enum value */
	CKM_SHA512_224 = 42,
	/** An enum value */
	CKM_SHA512_224_HMAC = 43,
	/** An enum value */
	CKM_SHA512_224_HMAC_GENERAL = 44,
	/** An enum value */
	CKM_SHA512_224_KEY_DERIVATION = 45,
	/** An enum value */
	CKM_SHA512_256 = 46,
	/** An enum value */
	CKM_SHA512_256_HMAC = 47,
	/** An enum value */
	CKM_SHA512_256_HMAC_GENERAL = 48,
	/** An enum value */
	CKM_SHA512_256_KEY_DERIVATION = 49,
	/** An enum value */
	CKM_SHA512_T = 50,
	/** An enum value */
	CKM_SHA512_T_HMAC = 51,
	/** An enum value */
	CKM_SHA512_T_HMAC_GENERAL = 52,
	/** An enum value */
	CKM_SHA512_T_KEY_DERIVATION = 53,
	/** An enum value */
	CKM_SHA3_256_RSA_PKCS = 54,
	/** An enum value */
	CKM_SHA3_384_RSA_PKCS = 55,
	/** An enum value */
	CKM_SHA3_512_RSA_PKCS = 56,
	/** An enum value */
	CKM_SHA3_256_RSA_PKCS_PSS = 57,
	/** An enum value */
	CKM_SHA3_384_RSA_PKCS_PSS = 58,
	/** An enum value */
	CKM_SHA3_512_RSA_PKCS_PSS = 59,
	/** An enum value */
	CKM_SHA3_224_RSA_PKCS = 60,
	/** An enum value */
	CKM_SHA3_224_RSA_PKCS_PSS = 61,
	/** An enum value */
	CKM_RC2_KEY_GEN = 62,
	/** An enum value */
	CKM_RC2_ECB = 63,
	/** An enum value */
	CKM_RC2_CBC = 64,
	/** An enum value */
	CKM_RC2_MAC = 65,
	/** An enum value */
	CKM_RC2_MAC_GENERAL = 66,
	/** An enum value */
	CKM_RC2_CBC_PAD = 67,
	/** An enum value */
	CKM_RC4_KEY_GEN = 68,
	/** An enum value */
	CKM_RC4 = 69,
	/** An enum value */
	CKM_DES_KEY_GEN = 70,
	/** An enum value */
	CKM_DES_ECB = 71,
	/** An enum value */
	CKM_DES_CBC = 72,
	/** An enum value */
	CKM_DES_MAC = 73,
	/** An enum value */
	CKM_DES_MAC_GENERAL = 74,
	/** An enum value */
	CKM_DES_CBC_PAD = 75,
	/** An enum value */
	CKM_DES2_KEY_GEN = 76,
	/** An enum value */
	CKM_DES3_KEY_GEN = 77,
	/** An enum value */
	CKM_DES3_ECB = 78,
	/** An enum value */
	CKM_DES3_CBC = 79,
	/** An enum value */
	CKM_DES3_MAC = 80,
	/** An enum value */
	CKM_DES3_MAC_GENERAL = 81,
	/** An enum value */
	CKM_DES3_CBC_PAD = 82,
	/** An enum value */
	CKM_DES3_CMAC_GENERAL = 83,
	/** An enum value */
	CKM_DES3_CMAC = 84,
	/** An enum value */
	CKM_CDMF_KEY_GEN = 85,
	/** An enum value */
	CKM_CDMF_ECB = 86,
	/** An enum value */
	CKM_CDMF_CBC = 87,
	/** An enum value */
	CKM_CDMF_MAC = 88,
	/** An enum value */
	CKM_CDMF_MAC_GENERAL = 89,
	/** An enum value */
	CKM_CDMF_CBC_PAD = 90,
	/** An enum value */
	CKM_DES_OFB64 = 91,
	/** An enum value */
	CKM_DES_OFB8 = 92,
	/** An enum value */
	CKM_DES_CFB64 = 93,
	/** An enum value */
	CKM_DES_CFB8 = 94,
	/** An enum value */
	CKM_MD2 = 95,
	/** An enum value */
	CKM_MD2_HMAC = 96,
	/** An enum value */
	CKM_MD2_HMAC_GENERAL = 97,
	/** An enum value */
	CKM_MD5 = 98,
	/** An enum value */
	CKM_MD5_HMAC = 99,
	/** An enum value */
	CKM_MD5_HMAC_GENERAL = 100,
	/** An enum value */
	CKM_SHA_1 = 101,
	/** An enum value */
	CKM_SHA_1_HMAC = 102,
	/** An enum value */
	CKM_SHA_1_HMAC_GENERAL = 103,
	/** An enum value */
	CKM_RIPEMD128 = 104,
	/** An enum value */
	CKM_RIPEMD128_HMAC = 105,
	/** An enum value */
	CKM_RIPEMD128_HMAC_GENERAL = 106,
	/** An enum value */
	CKM_RIPEMD160 = 107,
	/** An enum value */
	CKM_RIPEMD160_HMAC = 108,
	/** An enum value */
	CKM_RIPEMD160_HMAC_GENERAL = 109,
	/** An enum value */
	CKM_SHA256 = 110,
	/** An enum value */
	CKM_SHA256_HMAC = 111,
	/** An enum value */
	CKM_SHA256_HMAC_GENERAL = 112,
	/** An enum value */
	CKM_SHA224 = 113,
	/** An enum value */
	CKM_SHA224_HMAC = 114,
	/** An enum value */
	CKM_SHA224_HMAC_GENERAL = 115,
	/** An enum value */
	CKM_SHA384 = 116,
	/** An enum value */
	CKM_SHA384_HMAC = 117,
	/** An enum value */
	CKM_SHA384_HMAC_GENERAL = 118,
	/** An enum value */
	CKM_SHA512 = 119,
	/** An enum value */
	CKM_SHA512_HMAC = 120,
	/** An enum value */
	CKM_SHA512_HMAC_GENERAL = 121,
	/** An enum value */
	CKM_SECURID_KEY_GEN = 122,
	/** An enum value */
	CKM_SECURID = 123,
	/** An enum value */
	CKM_HOTP_KEY_GEN = 124,
	/** An enum value */
	CKM_HOTP = 125,
	/** An enum value */
	CKM_ACTI = 126,
	/** An enum value */
	CKM_ACTI_KEY_GEN = 127,
	/** An enum value */
	CKM_SHA3_256 = 128,
	/** An enum value */
	CKM_SHA3_256_HMAC = 129,
	/** An enum value */
	CKM_SHA3_256_HMAC_GENERAL = 130,
	/** An enum value */
	CKM_SHA3_256_KEY_GEN = 131,
	/** An enum value */
	CKM_SHA3_224 = 132,
	/** An enum value */
	CKM_SHA3_224_HMAC = 133,
	/** An enum value */
	CKM_SHA3_224_HMAC_GENERAL = 134,
	/** An enum value */
	CKM_SHA3_224_KEY_GEN = 135,
	/** An enum value */
	CKM_SHA3_384 = 136,
	/** An enum value */
	CKM_SHA3_384_HMAC = 137,
	/** An enum value */
	CKM_SHA3_384_HMAC_GENERAL = 138,
	/** An enum value */
	CKM_SHA3_384_KEY_GEN = 139,
	/** An enum value */
	CKM_SHA3_512 = 140,
	/** An enum value */
	CKM_SHA3_512_HMAC = 141,
	/** An enum value */
	CKM_SHA3_512_HMAC_GENERAL = 142,
	/** An enum value */
	CKM_SHA3_512_KEY_GEN = 143,
	/** An enum value */
	CKM_CAST_KEY_GEN = 144,
	/** An enum value */
	CKM_CAST_ECB = 145,
	/** An enum value */
	CKM_CAST_CBC = 146,
	/** An enum value */
	CKM_CAST_MAC = 147,
	/** An enum value */
	CKM_CAST_MAC_GENERAL = 148,
	/** An enum value */
	CKM_CAST_CBC_PAD = 149,
	/** An enum value */
	CKM_CAST3_KEY_GEN = 150,
	/** An enum value */
	CKM_CAST3_ECB = 151,
	/** An enum value */
	CKM_CAST3_CBC = 152,
	/** An enum value */
	CKM_CAST3_MAC = 153,
	/** An enum value */
	CKM_CAST3_MAC_GENERAL = 154,
	/** An enum value */
	CKM_CAST3_CBC_PAD = 155,
	/** An enum value */
	CKM_CAST5_KEY_GEN = 156,
	/** An enum value */
	CKM_CAST128_KEY_GEN = 157,
	/** An enum value */
	CKM_CAST5_ECB = 158,
	/** An enum value */
	CKM_CAST128_ECB = 159,
	/** An enum value */
	CKM_CAST5_CBC = 160,
	/** An enum value */
	CKM_CAST128_CBC = 161,
	/** An enum value */
	CKM_CAST5_MAC = 162,
	/** An enum value */
	CKM_CAST128_MAC = 163,
	/** An enum value */
	CKM_CAST5_MAC_GENERAL = 164,
	/** An enum value */
	CKM_CAST128_MAC_GENERAL = 165,
	/** An enum value */
	CKM_CAST5_CBC_PAD = 166,
	/** An enum value */
	CKM_CAST128_CBC_PAD = 167,
	/** An enum value */
	CKM_RC5_KEY_GEN = 168,
	/** An enum value */
	CKM_RC5_ECB = 169,
	/** An enum value */
	CKM_RC5_CBC = 170,
	/** An enum value */
	CKM_RC5_MAC = 171,
	/** An enum value */
	CKM_RC5_MAC_GENERAL = 172,
	/** An enum value */
	CKM_RC5_CBC_PAD = 173,
	/** An enum value */
	CKM_IDEA_KEY_GEN = 174,
	/** An enum value */
	CKM_IDEA_ECB = 175,
	/** An enum value */
	CKM_IDEA_CBC = 176,
	/** An enum value */
	CKM_IDEA_MAC = 177,
	/** An enum value */
	CKM_IDEA_MAC_GENERAL = 178,
	/** An enum value */
	CKM_IDEA_CBC_PAD = 179,
	/** An enum value */
	CKM_GENERIC_SECRET_KEY_GEN = 180,
	/** An enum value */
	CKM_CONCATENATE_BASE_AND_KEY = 181,
	/** An enum value */
	CKM_CONCATENATE_BASE_AND_DATA = 182,
	/** An enum value */
	CKM_CONCATENATE_DATA_AND_BASE = 183,
	/** An enum value */
	CKM_XOR_BASE_AND_DATA = 184,
	/** An enum value */
	CKM_EXTRACT_KEY_FROM_KEY = 185,
	/** An enum value */
	CKM_SSL3_PRE_MASTER_KEY_GEN = 186,
	/** An enum value */
	CKM_SSL3_MASTER_KEY_DERIVE = 187,
	/** An enum value */
	CKM_SSL3_KEY_AND_MAC_DERIVE = 188,
	/** An enum value */
	CKM_SSL3_MASTER_KEY_DERIVE_DH = 189,
	/** An enum value */
	CKM_TLS_PRE_MASTER_KEY_GEN = 190,
	/** An enum value */
	CKM_TLS_MASTER_KEY_DERIVE = 191,
	/** An enum value */
	CKM_TLS_KEY_AND_MAC_DERIVE = 192,
	/** An enum value */
	CKM_TLS_MASTER_KEY_DERIVE_DH = 193,
	/** An enum value */
	CKM_TLS_PRF = 194,
	/** An enum value */
	CKM_SSL3_MD5_MAC = 195,
	/** An enum value */
	CKM_SSL3_SHA1_MAC = 196,
	/** An enum value */
	CKM_MD5_KEY_DERIVATION = 197,
	/** An enum value */
	CKM_MD2_KEY_DERIVATION = 198,
	/** An enum value */
	CKM_SHA1_KEY_DERIVATION = 199,
	/** An enum value */
	CKM_SHA256_KEY_DERIVATION = 200,
	/** An enum value */
	CKM_SHA384_KEY_DERIVATION = 201,
	/** An enum value */
	CKM_SHA512_KEY_DERIVATION = 202,
	/** An enum value */
	CKM_SHA224_KEY_DERIVATION = 203,
	/** An enum value */
	CKM_SHA3_256_KEY_DERIVE = 204,
	/** An enum value */
	CKM_SHA3_224_KEY_DERIVE = 205,
	/** An enum value */
	CKM_SHA3_384_KEY_DERIVE = 206,
	/** An enum value */
	CKM_SHA3_512_KEY_DERIVE = 207,
	/** An enum value */
	CKM_SHAKE_128_KEY_DERIVE = 208,
	/** An enum value */
	CKM_SHAKE_256_KEY_DERIVE = 209,
	/** An enum value */
	CKM_PBE_MD2_DES_CBC = 210,
	/** An enum value */
	CKM_PBE_MD5_DES_CBC = 211,
	/** An enum value */
	CKM_PBE_MD5_CAST_CBC = 212,
	/** An enum value */
	CKM_PBE_MD5_CAST3_CBC = 213,
	/** An enum value */
	CKM_PBE_MD5_CAST5_CBC = 214,
	/** An enum value */
	CKM_PBE_MD5_CAST128_CBC = 215,
	/** An enum value */
	CKM_PBE_SHA1_CAST5_CBC = 216,
	/** An enum value */
	CKM_PBE_SHA1_CAST128_CBC = 217,
	/** An enum value */
	CKM_PBE_SHA1_RC4_128 = 218,
	/** An enum value */
	CKM_PBE_SHA1_RC4_40 = 219,
	/** An enum value */
	CKM_PBE_SHA1_DES3_EDE_CBC = 220,
	/** An enum value */
	CKM_PBE_SHA1_DES2_EDE_CBC = 221,
	/** An enum value */
	CKM_PBE_SHA1_RC2_128_CBC = 222,
	/** An enum value */
	CKM_PBE_SHA1_RC2_40_CBC = 223,
	/** An enum value */
	CKM_PKCS5_PBKD2 = 224,
	/** An enum value */
	CKM_PBA_SHA1_WITH_SHA1_HMAC = 225,
	/** An enum value */
	CKM_WTLS_PRE_MASTER_KEY_GEN = 226,
	/** An enum value */
	CKM_WTLS_MASTER_KEY_DERIVE = 227,
	/** An enum value */
	CKM_WTLS_MASTER_KEY_DERIVE_DH_ECC = 228,
	/** An enum value */
	CKM_WTLS_PRF = 229,
	/** An enum value */
	CKM_WTLS_SERVER_KEY_AND_MAC_DERIVE = 230,
	/** An enum value */
	CKM_WTLS_CLIENT_KEY_AND_MAC_DERIVE = 231,
	/** An enum value */
	CKM_TLS10_MAC_SERVER = 232,
	/** An enum value */
	CKM_TLS10_MAC_CLIENT = 233,
	/** An enum value */
	CKM_TLS12_MAC = 234,
	/** An enum value */
	CKM_TLS12_KDF = 235,
	/** An enum value */
	CKM_TLS12_MASTER_KEY_DERIVE = 236,
	/** An enum value */
	CKM_TLS12_KEY_AND_MAC_DERIVE = 237,
	/** An enum value */
	CKM_TLS12_MASTER_KEY_DERIVE_DH = 238,
	/** An enum value */
	CKM_TLS12_KEY_SAFE_DERIVE = 239,
	/** An enum value */
	CKM_TLS_MAC = 240,
	/** An enum value */
	CKM_TLS_KDF = 241,
	/** An enum value */
	CKM_KEY_WRAP_LYNKS = 242,
	/** An enum value */
	CKM_KEY_WRAP_SET_OAEP = 243,
	/** An enum value */
	CKM_CMS_SIG = 244,
	/** An enum value */
	CKM_KIP_DERIVE = 245,
	/** An enum value */
	CKM_KIP_WRAP = 246,
	/** An enum value */
	CKM_KIP_MAC = 247,
	/** An enum value */
	CKM_CAMELLIA_KEY_GEN = 248,
	/** An enum value */
	CKM_CAMELLIA_ECB = 249,
	/** An enum value */
	CKM_CAMELLIA_CBC = 250,
	/** An enum value */
	CKM_CAMELLIA_MAC = 251,
	/** An enum value */
	CKM_CAMELLIA_MAC_GENERAL = 252,
	/** An enum value */
	CKM_CAMELLIA_CBC_PAD = 253,
	/** An enum value */
	CKM_CAMELLIA_ECB_ENCRYPT_DATA = 254,
	/** An enum value */
	CKM_CAMELLIA_CBC_ENCRYPT_DATA = 255,
	/** An enum value */
	CKM_CAMELLIA_CTR = 256,
	/** An enum value */
	CKM_ARIA_KEY_GEN = 257,
	/** An enum value */
	CKM_ARIA_ECB = 258,
	/** An enum value */
	CKM_ARIA_CBC = 259,
	/** An enum value */
	CKM_ARIA_MAC = 260,
	/** An enum value */
	CKM_ARIA_MAC_GENERAL = 261,
	/** An enum value */
	CKM_ARIA_CBC_PAD = 262,
	/** An enum value */
	CKM_ARIA_ECB_ENCRYPT_DATA = 263,
	/** An enum value */
	CKM_ARIA_CBC_ENCRYPT_DATA = 264,
	/** An enum value */
	CKM_SEED_KEY_GEN = 265,
	/** An enum value */
	CKM_SEED_ECB = 266,
	/** An enum value */
	CKM_SEED_CBC = 267,
	/** An enum value */
	CKM_SEED_MAC = 268,
	/** An enum value */
	CKM_SEED_MAC_GENERAL = 269,
	/** An enum value */
	CKM_SEED_CBC_PAD = 270,
	/** An enum value */
	CKM_SEED_ECB_ENCRYPT_DATA = 271,
	/** An enum value */
	CKM_SEED_CBC_ENCRYPT_DATA = 272,
	/** An enum value */
	CKM_SKIPJACK_KEY_GEN = 273,
	/** An enum value */
	CKM_SKIPJACK_ECB64 = 274,
	/** An enum value */
	CKM_SKIPJACK_CBC64 = 275,
	/** An enum value */
	CKM_SKIPJACK_OFB64 = 276,
	/** An enum value */
	CKM_SKIPJACK_CFB64 = 277,
	/** An enum value */
	CKM_SKIPJACK_CFB32 = 278,
	/** An enum value */
	CKM_SKIPJACK_CFB16 = 279,
	/** An enum value */
	CKM_SKIPJACK_CFB8 = 280,
	/** An enum value */
	CKM_SKIPJACK_WRAP = 281,
	/** An enum value */
	CKM_SKIPJACK_PRIVATE_WRAP = 282,
	/** An enum value */
	CKM_SKIPJACK_RELAYX = 283,
	/** An enum value */
	CKM_KEA_KEY_PAIR_GEN = 284,
	/** An enum value */
	CKM_KEA_KEY_DERIVE = 285,
	/** An enum value */
	CKM_KEA_DERIVE = 286,
	/** An enum value */
	CKM_FORTEZZA_TIMESTAMP = 287,
	/** An enum value */
	CKM_BATON_KEY_GEN = 288,
	/** An enum value */
	CKM_BATON_ECB128 = 289,
	/** An enum value */
	CKM_BATON_ECB96 = 290,
	/** An enum value */
	CKM_BATON_CBC128 = 291,
	/** An enum value */
	CKM_BATON_COUNTER = 292,
	/** An enum value */
	CKM_BATON_SHUFFLE = 293,
	/** An enum value */
	CKM_BATON_WRAP = 294,
	/** An enum value */
	CKM_ECDSA_KEY_PAIR_GEN = 295,
	/** An enum value */
	CKM_EC_KEY_PAIR_GEN = 296,
	/** An enum value */
	CKM_ECDSA = 297,
	/** An enum value */
	CKM_ECDSA_SHA1 = 298,
	/** An enum value */
	CKM_ECDSA_SHA224 = 299,
	/** An enum value */
	CKM_ECDSA_SHA256 = 300,
	/** An enum value */
	CKM_ECDSA_SHA384 = 301,
	/** An enum value */
	CKM_ECDSA_SHA512 = 302,
	/** An enum value */
	CKM_ECDH1_DERIVE = 303,
	/** An enum value */
	CKM_ECDH1_COFACTOR_DERIVE = 304,
	/** An enum value */
	CKM_ECMQV_DERIVE = 305,
	/** An enum value */
	CKM_ECDH_AES_KEY_WRAP = 306,
	/** An enum value */
	CKM_RSA_AES_KEY_WRAP = 307,
	/** An enum value */
	CKM_JUNIPER_KEY_GEN = 308,
	/** An enum value */
	CKM_JUNIPER_ECB128 = 309,
	/** An enum value */
	CKM_JUNIPER_CBC128 = 310,
	/** An enum value */
	CKM_JUNIPER_COUNTER = 311,
	/** An enum value */
	CKM_JUNIPER_SHUFFLE = 312,
	/** An enum value */
	CKM_JUNIPER_WRAP = 313,
	/** An enum value */
	CKM_FASTHASH = 314,
	/** An enum value */
	CKM_AES_KEY_GEN = 315,
	/** An enum value */
	CKM_AES_ECB = 316,
	/** An enum value */
	CKM_AES_CBC = 317,
	/** An enum value */
	CKM_AES_MAC = 318,
	/** An enum value */
	CKM_AES_MAC_GENERAL = 319,
	/** An enum value */
	CKM_AES_CBC_PAD = 320,
	/** An enum value */
	CKM_AES_CTR = 321,
	/** An enum value */
	CKM_AES_GCM = 322,
	/** An enum value */
	CKM_AES_CCM = 323,
	/** An enum value */
	CKM_AES_CMAC_GENERAL = 324,
	/** An enum value */
	CKM_AES_CMAC = 325,
	/** An enum value */
	CKM_AES_CTS = 326,
	/** An enum value */
	CKM_AES_XCBC_MAC = 327,
	/** An enum value */
	CKM_AES_XCBC_MAC_96 = 328,
	/** An enum value */
	CKM_AES_GMAC = 329,
	/** An enum value */
	CKM_BLOWFISH_KEY_GEN = 330,
	/** An enum value */
	CKM_BLOWFISH_CBC = 331,
	/** An enum value */
	CKM_TWOFISH_KEY_GEN = 332,
	/** An enum value */
	CKM_TWOFISH_CBC = 333,
	/** An enum value */
	CKM_BLOWFISH_CBC_PAD = 334,
	/** An enum value */
	CKM_TWOFISH_CBC_PAD = 335,
	/** An enum value */
	CKM_DES_ECB_ENCRYPT_DATA = 336,
	/** An enum value */
	CKM_DES_CBC_ENCRYPT_DATA = 337,
	/** An enum value */
	CKM_DES3_ECB_ENCRYPT_DATA = 338,
	/** An enum value */
	CKM_DES3_CBC_ENCRYPT_DATA = 339,
	/** An enum value */
	CKM_AES_ECB_ENCRYPT_DATA = 340,
	/** An enum value */
	CKM_AES_CBC_ENCRYPT_DATA = 341,
	/** An enum value */
	CKM_GOSTR3410_KEY_PAIR_GEN = 342,
	/** An enum value */
	CKM_GOSTR3410 = 343,
	/** An enum value */
	CKM_GOSTR3410_WITH_GOSTR3411 = 344,
	/** An enum value */
	CKM_GOSTR3410_KEY_WRAP = 345,
	/** An enum value */
	CKM_GOSTR3410_DERIVE = 346,
	/** An enum value */
	CKM_GOSTR3411 = 347,
	/** An enum value */
	CKM_GOSTR3411_HMAC = 348,
	/** An enum value */
	CKM_GOST28147_KEY_GEN = 349,
	/** An enum value */
	CKM_GOST28147_ECB = 350,
	/** An enum value */
	CKM_GOST28147 = 351,
	/** An enum value */
	CKM_GOST28147_MAC = 352,
	/** An enum value */
	CKM_GOST28147_KEY_WRAP = 353,
	/** An enum value */
	CKM_DSA_PARAMETER_GEN = 354,
	/** An enum value */
	CKM_DH_PKCS_PARAMETER_GEN = 355,
	/** An enum value */
	CKM_X9_42_DH_PARAMETER_GEN = 356,
	/** An enum value */
	CKM_DSA_PROBABLISTIC_PARAMETER_GEN = 357,
	/** An enum value */
	CKM_DSA_SHAWE_TAYLOR_PARAMETER_GEN = 358,
	/** An enum value */
	CKM_AES_OFB = 359,
	/** An enum value */
	CKM_AES_CFB64 = 360,
	/** An enum value */
	CKM_AES_CFB8 = 361,
	/** An enum value */
	CKM_AES_CFB128 = 362,
	/** An enum value */
	CKM_AES_CFB1 = 363,
	/** An enum value */
	CKM_AES_KEY_WRAP = 364,
	/** An enum value */
	CKM_AES_KEY_WRAP_PAD = 365,
	/** An enum value */
	CKM_RSA_PKCS_TPM_1_1 = 366,
	/** An enum value */
	CKM_RSA_PKCS_OAEP_TPM_1_1 = 367,
	/** An enum value */
	CKM_VENDOR_DEFINED = 368,
}

