/**
 * Code generated by protoc-gen-tsjson. DO NOT EDIT.
 * versions:
 * 	protoc-gen-tsjson v0.5.3
 * 	protoc            v3.10.1
 * source: objectclass.proto
 */


/** An enum */
export enum ObjectClass {
	/** An enum value */
	CKO_UNDEFINED_UNKNOWN = 0,
	/** An enum value */
	CKO_DATA = 1,
	/** An enum value */
	CKO_CERTIFICATE = 2,
	/** An enum value */
	CKO_PUBLIC_KEY = 3,
	/** An enum value */
	CKO_PRIVATE_KEY = 4,
	/** An enum value */
	CKO_SECRET_KEY = 5,
	/** An enum value */
	CKO_HW_FEATURE = 6,
	/** An enum value */
	CKO_DOMAIN_PARAMETERS = 7,
	/** An enum value */
	CKO_MECHANISM = 8,
	/** An enum value */
	CKO_OTP_KEY = 9,
	/** An enum value */
	CKO_VENDOR_DEFINED = 10,
}

