// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.10.1
// source: certificatetypes.proto

package padlockpb

import (
	_ "github.com/LLKennedy/protoc-gen-tsjson/tsjsonpb"
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type CertificateType int32

const (
	CertificateType_CKC_UNDEFINED_UNKNOWN CertificateType = 0
	CertificateType_CKC_X_509             CertificateType = 1
	CertificateType_CKC_X_509_ATTR_CERT   CertificateType = 2
	CertificateType_CKC_WTLS              CertificateType = 3
	CertificateType_CKC_VENDOR_DEFINED    CertificateType = 4
)

// Enum value maps for CertificateType.
var (
	CertificateType_name = map[int32]string{
		0: "CKC_UNDEFINED_UNKNOWN",
		1: "CKC_X_509",
		2: "CKC_X_509_ATTR_CERT",
		3: "CKC_WTLS",
		4: "CKC_VENDOR_DEFINED",
	}
	CertificateType_value = map[string]int32{
		"CKC_UNDEFINED_UNKNOWN": 0,
		"CKC_X_509":             1,
		"CKC_X_509_ATTR_CERT":   2,
		"CKC_WTLS":              3,
		"CKC_VENDOR_DEFINED":    4,
	}
)

func (x CertificateType) Enum() *CertificateType {
	p := new(CertificateType)
	*p = x
	return p
}

func (x CertificateType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CertificateType) Descriptor() protoreflect.EnumDescriptor {
	return file_certificatetypes_proto_enumTypes[0].Descriptor()
}

func (CertificateType) Type() protoreflect.EnumType {
	return &file_certificatetypes_proto_enumTypes[0]
}

func (x CertificateType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CertificateType.Descriptor instead.
func (CertificateType) EnumDescriptor() ([]byte, []int) {
	return file_certificatetypes_proto_rawDescGZIP(), []int{0}
}

var File_certificatetypes_proto protoreflect.FileDescriptor

var file_certificatetypes_proto_rawDesc = []byte{
	0x0a, 0x16, 0x63, 0x65, 0x72, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x65, 0x74, 0x79, 0x70,
	0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x70, 0x61, 0x64, 0x6c, 0x6f, 0x63,
	0x6b, 0x1a, 0x0c, 0x74, 0x73, 0x6a, 0x73, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2a,
	0x7a, 0x0a, 0x0f, 0x43, 0x65, 0x72, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x65, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x19, 0x0a, 0x15, 0x43, 0x4b, 0x43, 0x5f, 0x55, 0x4e, 0x44, 0x45, 0x46, 0x49,
	0x4e, 0x45, 0x44, 0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x0d, 0x0a,
	0x09, 0x43, 0x4b, 0x43, 0x5f, 0x58, 0x5f, 0x35, 0x30, 0x39, 0x10, 0x01, 0x12, 0x17, 0x0a, 0x13,
	0x43, 0x4b, 0x43, 0x5f, 0x58, 0x5f, 0x35, 0x30, 0x39, 0x5f, 0x41, 0x54, 0x54, 0x52, 0x5f, 0x43,
	0x45, 0x52, 0x54, 0x10, 0x02, 0x12, 0x0c, 0x0a, 0x08, 0x43, 0x4b, 0x43, 0x5f, 0x57, 0x54, 0x4c,
	0x53, 0x10, 0x03, 0x12, 0x16, 0x0a, 0x12, 0x43, 0x4b, 0x43, 0x5f, 0x56, 0x45, 0x4e, 0x44, 0x4f,
	0x52, 0x5f, 0x44, 0x45, 0x46, 0x49, 0x4e, 0x45, 0x44, 0x10, 0x04, 0x42, 0x48, 0x5a, 0x26, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x4c, 0x4c, 0x4b, 0x65, 0x6e, 0x6e,
	0x65, 0x64, 0x79, 0x2f, 0x70, 0x61, 0x64, 0x6c, 0x6f, 0x63, 0x6b, 0x2f, 0x70, 0x61, 0x64, 0x6c,
	0x6f, 0x63, 0x6b, 0x70, 0x62, 0x82, 0xd9, 0x66, 0x10, 0x40, 0x6c, 0x6c, 0x6b, 0x64, 0x65, 0x6d,
	0x6f, 0x2f, 0x70, 0x61, 0x64, 0x6c, 0x6f, 0x63, 0x6b, 0x8a, 0xd9, 0x66, 0x08, 0x6b, 0x65, 0x79,
	0x74, 0x79, 0x70, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_certificatetypes_proto_rawDescOnce sync.Once
	file_certificatetypes_proto_rawDescData = file_certificatetypes_proto_rawDesc
)

func file_certificatetypes_proto_rawDescGZIP() []byte {
	file_certificatetypes_proto_rawDescOnce.Do(func() {
		file_certificatetypes_proto_rawDescData = protoimpl.X.CompressGZIP(file_certificatetypes_proto_rawDescData)
	})
	return file_certificatetypes_proto_rawDescData
}

var file_certificatetypes_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_certificatetypes_proto_goTypes = []interface{}{
	(CertificateType)(0), // 0: padlock.CertificateType
}
var file_certificatetypes_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_certificatetypes_proto_init() }
func file_certificatetypes_proto_init() {
	if File_certificatetypes_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_certificatetypes_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_certificatetypes_proto_goTypes,
		DependencyIndexes: file_certificatetypes_proto_depIdxs,
		EnumInfos:         file_certificatetypes_proto_enumTypes,
	}.Build()
	File_certificatetypes_proto = out.File
	file_certificatetypes_proto_rawDesc = nil
	file_certificatetypes_proto_goTypes = nil
	file_certificatetypes_proto_depIdxs = nil
}
