// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.10.1
// source: padlock.proto

package padlockpb

import (
	_ "github.com/LLKennedy/protoc-gen-tsjson/tsjsonpb"
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type AuthHello struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AuthHello) Reset() {
	*x = AuthHello{}
	if protoimpl.UnsafeEnabled {
		mi := &file_padlock_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthHello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthHello) ProtoMessage() {}

func (x *AuthHello) ProtoReflect() protoreflect.Message {
	mi := &file_padlock_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthHello.ProtoReflect.Descriptor instead.
func (*AuthHello) Descriptor() ([]byte, []int) {
	return file_padlock_proto_rawDescGZIP(), []int{0}
}

type AuthToken struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *AuthToken) Reset() {
	*x = AuthToken{}
	if protoimpl.UnsafeEnabled {
		mi := &file_padlock_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthToken) ProtoMessage() {}

func (x *AuthToken) ProtoReflect() protoreflect.Message {
	mi := &file_padlock_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthToken.ProtoReflect.Descriptor instead.
func (*AuthToken) Descriptor() ([]byte, []int) {
	return file_padlock_proto_rawDescGZIP(), []int{1}
}

func (x *AuthToken) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type ApplicationListModulesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Auth *AuthToken `protobuf:"bytes,1,opt,name=auth,proto3" json:"auth,omitempty"`
}

func (x *ApplicationListModulesRequest) Reset() {
	*x = ApplicationListModulesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_padlock_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ApplicationListModulesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplicationListModulesRequest) ProtoMessage() {}

func (x *ApplicationListModulesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_padlock_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplicationListModulesRequest.ProtoReflect.Descriptor instead.
func (*ApplicationListModulesRequest) Descriptor() ([]byte, []int) {
	return file_padlock_proto_rawDescGZIP(), []int{2}
}

func (x *ApplicationListModulesRequest) GetAuth() *AuthToken {
	if x != nil {
		return x.Auth
	}
	return nil
}

type ApplicationListModulesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Modules []string `protobuf:"bytes,1,rep,name=modules,proto3" json:"modules,omitempty"`
}

func (x *ApplicationListModulesResponse) Reset() {
	*x = ApplicationListModulesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_padlock_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ApplicationListModulesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplicationListModulesResponse) ProtoMessage() {}

func (x *ApplicationListModulesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_padlock_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplicationListModulesResponse.ProtoReflect.Descriptor instead.
func (*ApplicationListModulesResponse) Descriptor() ([]byte, []int) {
	return file_padlock_proto_rawDescGZIP(), []int{3}
}

func (x *ApplicationListModulesResponse) GetModules() []string {
	if x != nil {
		return x.Modules
	}
	return nil
}

type ApplicationConnectRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Auth   *AuthToken `protobuf:"bytes,1,opt,name=auth,proto3" json:"auth,omitempty"`
	Module string     `protobuf:"bytes,2,opt,name=module,proto3" json:"module,omitempty"`
}

func (x *ApplicationConnectRequest) Reset() {
	*x = ApplicationConnectRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_padlock_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ApplicationConnectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplicationConnectRequest) ProtoMessage() {}

func (x *ApplicationConnectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_padlock_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplicationConnectRequest.ProtoReflect.Descriptor instead.
func (*ApplicationConnectRequest) Descriptor() ([]byte, []int) {
	return file_padlock_proto_rawDescGZIP(), []int{4}
}

func (x *ApplicationConnectRequest) GetAuth() *AuthToken {
	if x != nil {
		return x.Auth
	}
	return nil
}

func (x *ApplicationConnectRequest) GetModule() string {
	if x != nil {
		return x.Module
	}
	return ""
}

type ApplicationConnectUpdate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Update:
	//	*ApplicationConnectUpdate_LoggedIn
	Update isApplicationConnectUpdate_Update `protobuf_oneof:"update"`
}

func (x *ApplicationConnectUpdate) Reset() {
	*x = ApplicationConnectUpdate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_padlock_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ApplicationConnectUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplicationConnectUpdate) ProtoMessage() {}

func (x *ApplicationConnectUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_padlock_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplicationConnectUpdate.ProtoReflect.Descriptor instead.
func (*ApplicationConnectUpdate) Descriptor() ([]byte, []int) {
	return file_padlock_proto_rawDescGZIP(), []int{5}
}

func (m *ApplicationConnectUpdate) GetUpdate() isApplicationConnectUpdate_Update {
	if m != nil {
		return m.Update
	}
	return nil
}

func (x *ApplicationConnectUpdate) GetLoggedIn() bool {
	if x, ok := x.GetUpdate().(*ApplicationConnectUpdate_LoggedIn); ok {
		return x.LoggedIn
	}
	return false
}

type isApplicationConnectUpdate_Update interface {
	isApplicationConnectUpdate_Update()
}

type ApplicationConnectUpdate_LoggedIn struct {
	LoggedIn bool `protobuf:"varint,1,opt,name=logged_in,json=loggedIn,proto3,oneof"`
}

func (*ApplicationConnectUpdate_LoggedIn) isApplicationConnectUpdate_Update() {}

type ModuleListSlotsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Auth *AuthToken `protobuf:"bytes,1,opt,name=auth,proto3" json:"auth,omitempty"`
}

func (x *ModuleListSlotsRequest) Reset() {
	*x = ModuleListSlotsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_padlock_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModuleListSlotsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModuleListSlotsRequest) ProtoMessage() {}

func (x *ModuleListSlotsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_padlock_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModuleListSlotsRequest.ProtoReflect.Descriptor instead.
func (*ModuleListSlotsRequest) Descriptor() ([]byte, []int) {
	return file_padlock_proto_rawDescGZIP(), []int{6}
}

func (x *ModuleListSlotsRequest) GetAuth() *AuthToken {
	if x != nil {
		return x.Auth
	}
	return nil
}

type ModuleListSlotsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Slots []*Slot `protobuf:"bytes,1,rep,name=slots,proto3" json:"slots,omitempty"`
}

func (x *ModuleListSlotsResponse) Reset() {
	*x = ModuleListSlotsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_padlock_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModuleListSlotsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModuleListSlotsResponse) ProtoMessage() {}

func (x *ModuleListSlotsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_padlock_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModuleListSlotsResponse.ProtoReflect.Descriptor instead.
func (*ModuleListSlotsResponse) Descriptor() ([]byte, []int) {
	return file_padlock_proto_rawDescGZIP(), []int{7}
}

func (x *ModuleListSlotsResponse) GetSlots() []*Slot {
	if x != nil {
		return x.Slots
	}
	return nil
}

var File_padlock_proto protoreflect.FileDescriptor

var file_padlock_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x70, 0x61, 0x64, 0x6c, 0x6f, 0x63, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x07, 0x70, 0x61, 0x64, 0x6c, 0x6f, 0x63, 0x6b, 0x1a, 0x0c, 0x74, 0x73, 0x6a, 0x73, 0x6f, 0x6e,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0c, 0x70, 0x6b, 0x63, 0x73, 0x31, 0x31, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x0b, 0x0a, 0x09, 0x41, 0x75, 0x74, 0x68, 0x48, 0x65, 0x6c, 0x6c,
	0x6f, 0x22, 0x1f, 0x0a, 0x09, 0x41, 0x75, 0x74, 0x68, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x12,
	0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x22, 0x47, 0x0a, 0x1d, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x4c, 0x69, 0x73, 0x74, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x26, 0x0a, 0x04, 0x61, 0x75, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x12, 0x2e, 0x70, 0x61, 0x64, 0x6c, 0x6f, 0x63, 0x6b, 0x2e, 0x41, 0x75, 0x74, 0x68,
	0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x04, 0x61, 0x75, 0x74, 0x68, 0x22, 0x3a, 0x0a, 0x1e, 0x41,
	0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4c, 0x69, 0x73, 0x74, 0x4d, 0x6f,
	0x64, 0x75, 0x6c, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07,
	0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x73, 0x22, 0x5b, 0x0a, 0x19, 0x41, 0x70, 0x70, 0x6c, 0x69,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x26, 0x0a, 0x04, 0x61, 0x75, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x61, 0x64, 0x6c, 0x6f, 0x63, 0x6b, 0x2e, 0x41, 0x75, 0x74,
	0x68, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x04, 0x61, 0x75, 0x74, 0x68, 0x12, 0x16, 0x0a, 0x06,
	0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6d, 0x6f,
	0x64, 0x75, 0x6c, 0x65, 0x22, 0x43, 0x0a, 0x18, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x12, 0x1d, 0x0a, 0x09, 0x6c, 0x6f, 0x67, 0x67, 0x65, 0x64, 0x5f, 0x69, 0x6e, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x08, 0x48, 0x00, 0x52, 0x08, 0x6c, 0x6f, 0x67, 0x67, 0x65, 0x64, 0x49, 0x6e, 0x42,
	0x08, 0x0a, 0x06, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x22, 0x40, 0x0a, 0x16, 0x4d, 0x6f, 0x64,
	0x75, 0x6c, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x6c, 0x6f, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x26, 0x0a, 0x04, 0x61, 0x75, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x12, 0x2e, 0x70, 0x61, 0x64, 0x6c, 0x6f, 0x63, 0x6b, 0x2e, 0x41, 0x75, 0x74, 0x68,
	0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x04, 0x61, 0x75, 0x74, 0x68, 0x22, 0x3e, 0x0a, 0x17, 0x4d,
	0x6f, 0x64, 0x75, 0x6c, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x6c, 0x6f, 0x74, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x23, 0x0a, 0x05, 0x73, 0x6c, 0x6f, 0x74, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x61, 0x64, 0x6c, 0x6f, 0x63, 0x6b, 0x2e,
	0x53, 0x6c, 0x6f, 0x74, 0x52, 0x05, 0x73, 0x6c, 0x6f, 0x74, 0x73, 0x32, 0xea, 0x02, 0x0a, 0x07,
	0x50, 0x61, 0x64, 0x6c, 0x6f, 0x63, 0x6b, 0x12, 0x33, 0x0a, 0x09, 0x50, 0x6f, 0x73, 0x74, 0x48,
	0x65, 0x6c, 0x6c, 0x6f, 0x12, 0x12, 0x2e, 0x70, 0x61, 0x64, 0x6c, 0x6f, 0x63, 0x6b, 0x2e, 0x41,
	0x75, 0x74, 0x68, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x1a, 0x12, 0x2e, 0x70, 0x61, 0x64, 0x6c, 0x6f,
	0x63, 0x6b, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x6d, 0x0a, 0x1a,
	0x50, 0x6f, 0x73, 0x74, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4c,
	0x69, 0x73, 0x74, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x73, 0x12, 0x26, 0x2e, 0x70, 0x61, 0x64,
	0x6c, 0x6f, 0x63, 0x6b, 0x2e, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x4c, 0x69, 0x73, 0x74, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x27, 0x2e, 0x70, 0x61, 0x64, 0x6c, 0x6f, 0x63, 0x6b, 0x2e, 0x41, 0x70, 0x70,
	0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4c, 0x69, 0x73, 0x74, 0x4d, 0x6f, 0x64, 0x75,
	0x6c, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x61, 0x0a, 0x16, 0x50,
	0x6f, 0x73, 0x74, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f,
	0x6e, 0x6e, 0x65, 0x63, 0x74, 0x12, 0x22, 0x2e, 0x70, 0x61, 0x64, 0x6c, 0x6f, 0x63, 0x6b, 0x2e,
	0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x6e, 0x6e, 0x65,
	0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x70, 0x61, 0x64, 0x6c,
	0x6f, 0x63, 0x6b, 0x2e, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x43,
	0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x30, 0x01, 0x12, 0x58,
	0x0a, 0x13, 0x50, 0x6f, 0x73, 0x74, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x4c, 0x69, 0x73, 0x74,
	0x53, 0x6c, 0x6f, 0x74, 0x73, 0x12, 0x1f, 0x2e, 0x70, 0x61, 0x64, 0x6c, 0x6f, 0x63, 0x6b, 0x2e,
	0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x6c, 0x6f, 0x74, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x70, 0x61, 0x64, 0x6c, 0x6f, 0x63, 0x6b,
	0x2e, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x6c, 0x6f, 0x74, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x47, 0x5a, 0x26, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x4c, 0x4c, 0x4b, 0x65, 0x6e, 0x6e, 0x65, 0x64, 0x79,
	0x2f, 0x70, 0x61, 0x64, 0x6c, 0x6f, 0x63, 0x6b, 0x2f, 0x70, 0x61, 0x64, 0x6c, 0x6f, 0x63, 0x6b,
	0x70, 0x62, 0x82, 0xd9, 0x66, 0x10, 0x40, 0x6c, 0x6c, 0x6b, 0x64, 0x65, 0x6d, 0x6f, 0x2f, 0x70,
	0x61, 0x64, 0x6c, 0x6f, 0x63, 0x6b, 0x8a, 0xd9, 0x66, 0x07, 0x70, 0x61, 0x64, 0x6c, 0x6f, 0x63,
	0x6b, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_padlock_proto_rawDescOnce sync.Once
	file_padlock_proto_rawDescData = file_padlock_proto_rawDesc
)

func file_padlock_proto_rawDescGZIP() []byte {
	file_padlock_proto_rawDescOnce.Do(func() {
		file_padlock_proto_rawDescData = protoimpl.X.CompressGZIP(file_padlock_proto_rawDescData)
	})
	return file_padlock_proto_rawDescData
}

var file_padlock_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_padlock_proto_goTypes = []interface{}{
	(*AuthHello)(nil),                      // 0: padlock.AuthHello
	(*AuthToken)(nil),                      // 1: padlock.AuthToken
	(*ApplicationListModulesRequest)(nil),  // 2: padlock.ApplicationListModulesRequest
	(*ApplicationListModulesResponse)(nil), // 3: padlock.ApplicationListModulesResponse
	(*ApplicationConnectRequest)(nil),      // 4: padlock.ApplicationConnectRequest
	(*ApplicationConnectUpdate)(nil),       // 5: padlock.ApplicationConnectUpdate
	(*ModuleListSlotsRequest)(nil),         // 6: padlock.ModuleListSlotsRequest
	(*ModuleListSlotsResponse)(nil),        // 7: padlock.ModuleListSlotsResponse
	(*Slot)(nil),                           // 8: padlock.Slot
}
var file_padlock_proto_depIdxs = []int32{
	1, // 0: padlock.ApplicationListModulesRequest.auth:type_name -> padlock.AuthToken
	1, // 1: padlock.ApplicationConnectRequest.auth:type_name -> padlock.AuthToken
	1, // 2: padlock.ModuleListSlotsRequest.auth:type_name -> padlock.AuthToken
	8, // 3: padlock.ModuleListSlotsResponse.slots:type_name -> padlock.Slot
	0, // 4: padlock.Padlock.PostHello:input_type -> padlock.AuthHello
	2, // 5: padlock.Padlock.PostApplicationListModules:input_type -> padlock.ApplicationListModulesRequest
	4, // 6: padlock.Padlock.PostApplicationConnect:input_type -> padlock.ApplicationConnectRequest
	6, // 7: padlock.Padlock.PostModuleListSlots:input_type -> padlock.ModuleListSlotsRequest
	1, // 8: padlock.Padlock.PostHello:output_type -> padlock.AuthToken
	3, // 9: padlock.Padlock.PostApplicationListModules:output_type -> padlock.ApplicationListModulesResponse
	5, // 10: padlock.Padlock.PostApplicationConnect:output_type -> padlock.ApplicationConnectUpdate
	7, // 11: padlock.Padlock.PostModuleListSlots:output_type -> padlock.ModuleListSlotsResponse
	8, // [8:12] is the sub-list for method output_type
	4, // [4:8] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_padlock_proto_init() }
func file_padlock_proto_init() {
	if File_padlock_proto != nil {
		return
	}
	file_pkcs11_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_padlock_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuthHello); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_padlock_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuthToken); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_padlock_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ApplicationListModulesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_padlock_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ApplicationListModulesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_padlock_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ApplicationConnectRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_padlock_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ApplicationConnectUpdate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_padlock_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModuleListSlotsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_padlock_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModuleListSlotsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_padlock_proto_msgTypes[5].OneofWrappers = []interface{}{
		(*ApplicationConnectUpdate_LoggedIn)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_padlock_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_padlock_proto_goTypes,
		DependencyIndexes: file_padlock_proto_depIdxs,
		MessageInfos:      file_padlock_proto_msgTypes,
	}.Build()
	File_padlock_proto = out.File
	file_padlock_proto_rawDesc = nil
	file_padlock_proto_goTypes = nil
	file_padlock_proto_depIdxs = nil
}
